<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.AppRunner" Version="4.0.100.15" />
    <PackageReference Include="AWSSDK.EC2" Version="4.0.124" />
    <PackageReference Include="AWSSDK.ECR" Version="4.0.101.7" />
    <PackageReference Include="AWSSDK.Lambda" Version="4.0.108.1" />
    <PackageReference Include="AWSSDK.S3" Version="4.0.103.4" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ServiceMonitor.Cloud\ServiceMonitor.Cloud.csproj" />
  </ItemGroup>

</Project>
